# Generated by Django 5.2.17 on 2026-09-29 09:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_attendancerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.PositiveIntegerField()),
                ('period_month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allowances', models.DecimalField(decimal_places=2, default=0, help_text='Transport, housing, and other allowances', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('tax_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, help_text='Loans, advances, and other deductions', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, help_text='Gross (basic + allowances + bonus) minus deductions', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='employees.employee')),
            ],
            options={
                'ordering': ['-period_year', '-period_month'],
                'unique_together': {('employee', 'period_year', 'period_month')},
            },
        ),
    ]
