# Generated by Django 5.2.17 on 2026-10-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_holiday_employee_manager_employeedocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='leave_days',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
